// Theme
export const THEME_SET = "THEME_SET";
export const THEMES = {
  DEFAULT: "DEFAULT",
  DARK: "DARK",
  LIGHT: "LIGHT",
  BLUE: "BLUE",
  GREEN: "GREEN",
  INDIGO: "INDIGO",
};

// Auth
export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_SIGN_IN_REQUEST = "AUTH_SIGN_IN_REQUEST";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_SIGN_IN_FAILURE = "AUTH_SIGN_IN_FAILURE";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_SIGN_UP_REQUEST = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";
export const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

// Accounts
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_FAILURE = "ADD_ACCOUNT_FAILURE";
export const ACCOUNTS_FETCH_SUCCESS = "ACCOUNTS_FETCH_SUCCESS";
export const ACCOUNTS_FETCH_FAILURE = "ACCOUNTS_FETCH_FAILURE";

// Child Accounts
export const CHILD_ACCOUNTS_FETCH_SUCCESS = "CHILD_ACCOUNTS_FETCH_SUCCESS";
export const CHILD_ACCOUNTS_FETCH_FAILURE = "CHILD_ACCOUNTS_FETCH_FAILURE";

// Users
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USERS_FETCH_FAILURE = "USERS_FETCH_FAILURE";

// Devices
export const DEVICES_FETCH_SUCCESS = "DEVICES_FETCH_SUCCESS";
export const DEVICES_FETCH_FAILURE = "DEVICES_FETCH_FAILURE";

// Scales
export const SCALES_FETCH_SUCCESS = "SCALES_FETCH_SUCCESS";
export const SCALES_FETCH_FAILURE = "SCALES_FETCH_FAILURE";
